version: '3.8'

services:
  nuxt:
    build: .
    container_name: balangom
    restart: unless-stopped
    environment:
      - NITRO_PORT=3000
      - NITRO_HOST=0.0.0.0
    ports:
      - "80:3000"
